// <auto-generated />
namespace PhuocCon.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Providertable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Providertable));
        
        string IMigrationMetadata.Id
        {
            get { return "201701061406093_Providertable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
